// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: sandbox/sandbox.proto

package sandboxproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	SandboxService_ConfigSandbox_FullMethodName = "/proto.sandboxproto.SandboxService/ConfigSandbox"
	SandboxService_DeploySandbox_FullMethodName = "/proto.sandboxproto.SandboxService/DeploySandbox"
)

// SandboxServiceClient is the client API for SandboxService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SandboxServiceClient interface {
	ConfigSandbox(ctx context.Context, in *ConfigSandboxRequest, opts ...grpc.CallOption) (*ConfigSandboxResponse, error)
	DeploySandbox(ctx context.Context, in *DeploySandboxRequest, opts ...grpc.CallOption) (*DeploySandboxResponse, error)
}

type sandboxServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSandboxServiceClient(cc grpc.ClientConnInterface) SandboxServiceClient {
	return &sandboxServiceClient{cc}
}

func (c *sandboxServiceClient) ConfigSandbox(ctx context.Context, in *ConfigSandboxRequest, opts ...grpc.CallOption) (*ConfigSandboxResponse, error) {
	out := new(ConfigSandboxResponse)
	err := c.cc.Invoke(ctx, SandboxService_ConfigSandbox_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) DeploySandbox(ctx context.Context, in *DeploySandboxRequest, opts ...grpc.CallOption) (*DeploySandboxResponse, error) {
	out := new(DeploySandboxResponse)
	err := c.cc.Invoke(ctx, SandboxService_DeploySandbox_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SandboxServiceServer is the server API for SandboxService service.
// All implementations must embed UnimplementedSandboxServiceServer
// for forward compatibility
type SandboxServiceServer interface {
	ConfigSandbox(context.Context, *ConfigSandboxRequest) (*ConfigSandboxResponse, error)
	DeploySandbox(context.Context, *DeploySandboxRequest) (*DeploySandboxResponse, error)
	mustEmbedUnimplementedSandboxServiceServer()
}

// UnimplementedSandboxServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSandboxServiceServer struct {
}

func (UnimplementedSandboxServiceServer) ConfigSandbox(context.Context, *ConfigSandboxRequest) (*ConfigSandboxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfigSandbox not implemented")
}
func (UnimplementedSandboxServiceServer) DeploySandbox(context.Context, *DeploySandboxRequest) (*DeploySandboxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeploySandbox not implemented")
}
func (UnimplementedSandboxServiceServer) mustEmbedUnimplementedSandboxServiceServer() {}

// UnsafeSandboxServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SandboxServiceServer will
// result in compilation errors.
type UnsafeSandboxServiceServer interface {
	mustEmbedUnimplementedSandboxServiceServer()
}

func RegisterSandboxServiceServer(s grpc.ServiceRegistrar, srv SandboxServiceServer) {
	s.RegisterService(&SandboxService_ServiceDesc, srv)
}

func _SandboxService_ConfigSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigSandboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).ConfigSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_ConfigSandbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).ConfigSandbox(ctx, req.(*ConfigSandboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_DeploySandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeploySandboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).DeploySandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_DeploySandbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).DeploySandbox(ctx, req.(*DeploySandboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SandboxService_ServiceDesc is the grpc.ServiceDesc for SandboxService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SandboxService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.sandboxproto.SandboxService",
	HandlerType: (*SandboxServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConfigSandbox",
			Handler:    _SandboxService_ConfigSandbox_Handler,
		},
		{
			MethodName: "DeploySandbox",
			Handler:    _SandboxService_DeploySandbox_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sandbox/sandbox.proto",
}
